language: go
go:
  - stable
  - "1.19"
  - "1.18"
  - "1.17"
install:
  - go get -t ./...
script:
# v1
  - go test -v .
  - go test -v ./exif-read-tool
# v2
  - cd v2
  - go test -v ./...
  - cd ..
# v3. Coverage reports comes from this.
  - cd v3
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - curl -s https://codecov.io/bash | bash
